-- QRoute database schema
-- Generated by: php bin/console schema:dump
--
-- Import this in phpMyAdmin if you would rather not run migrations.
-- Create an empty database first, select it, then use the Import tab.
--
-- This file is generated from migrations/, so it always matches what
-- `php bin/console migrate` would produce. Do not edit it by hand.

SET NAMES utf8mb4;
SET FOREIGN_KEY_CHECKS = 0;

-- ---------------------------------------------------------------
-- 001_init
-- ---------------------------------------------------------------

CREATE TABLE IF NOT EXISTS users (
        id               BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
        email            VARCHAR(191) NOT NULL,
        password_hash    VARCHAR(255) NOT NULL,
        display_name     VARCHAR(80)  NOT NULL DEFAULT '',
        plan             VARCHAR(20)  NOT NULL DEFAULT 'free',
        plan_expires_at  BIGINT      NULL,
        status           VARCHAR(20)  NOT NULL DEFAULT 'active',
        totp_secret      VARCHAR(64)  NULL,
        failed_logins    INT NOT NULL DEFAULT 0,
        locked_until     BIGINT      NULL,
        created_at       BIGINT      NOT NULL,
        updated_at       BIGINT      NOT NULL
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE UNIQUE INDEX idx_users_email ON users (email);

CREATE TABLE IF NOT EXISTS sessions (
        id          VARCHAR(64) NOT NULL PRIMARY KEY,
        user_id     BIGINT UNSIGNED      NOT NULL,
        ip_hash     VARCHAR(64) NOT NULL DEFAULT '',
        ua_hash     VARCHAR(64) NOT NULL DEFAULT '',
        created_at  BIGINT     NOT NULL,
        last_seen_at BIGINT    NOT NULL,
        expires_at  BIGINT     NOT NULL
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE INDEX idx_sessions_user ON sessions (user_id);

CREATE INDEX idx_sessions_exp ON sessions (expires_at);

CREATE TABLE IF NOT EXISTS links (
        id            BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
        user_id       BIGINT UNSIGNED       NOT NULL,
        slug          VARCHAR(32)  NOT NULL,
        title         VARCHAR(120) NOT NULL DEFAULT '',
        default_url   VARCHAR(2048) NOT NULL,
        is_active     INT NOT NULL DEFAULT 1,
        style_json    MEDIUMTEXT     NULL,
        scan_count    BIGINT      NOT NULL DEFAULT 0,
        last_scan_at  BIGINT      NULL,
        password_hash VARCHAR(255) NULL,
        expires_at    BIGINT      NULL,
        expired_url   VARCHAR(2048) NULL,
        archived_at   BIGINT      NULL,
        created_at    BIGINT      NOT NULL,
        updated_at    BIGINT      NOT NULL
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE UNIQUE INDEX idx_links_slug ON links (slug);

CREATE INDEX idx_links_user ON links (user_id, archived_at);

CREATE TABLE IF NOT EXISTS rules (
        id           BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
        link_id      BIGINT UNSIGNED       NOT NULL,
        label        VARCHAR(120) NOT NULL DEFAULT '',
        priority     INT NOT NULL DEFAULT 0,
        conditions   MEDIUMTEXT     NOT NULL,
        target_url   VARCHAR(2048) NOT NULL,
        is_active    INT NOT NULL DEFAULT 1,
        hits         BIGINT      NOT NULL DEFAULT 0,
        created_at   BIGINT      NOT NULL,
        updated_at   BIGINT      NOT NULL
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE INDEX idx_rules_link ON rules (link_id, priority);

CREATE TABLE IF NOT EXISTS scans (
        id           BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
        link_id      BIGINT UNSIGNED       NOT NULL,
        rule_id      BIGINT UNSIGNED       NULL,
        user_id      BIGINT UNSIGNED       NOT NULL,
        scanned_at   BIGINT      NOT NULL,
        day          VARCHAR(10)  NOT NULL,
        device       VARCHAR(16)  NOT NULL DEFAULT 'unknown',
        os           VARCHAR(24)  NOT NULL DEFAULT 'unknown',
        browser      VARCHAR(24)  NOT NULL DEFAULT 'unknown',
        country      VARCHAR(2)   NOT NULL DEFAULT '',
        lang         VARCHAR(8)   NOT NULL DEFAULT '',
        referer_host VARCHAR(191) NOT NULL DEFAULT '',
        is_bot       INT NOT NULL DEFAULT 0,
        is_unique    INT NOT NULL DEFAULT 1,
        visitor_hash VARCHAR(64)  NOT NULL DEFAULT ''
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE INDEX idx_scans_link_time ON scans (link_id, scanned_at);

CREATE INDEX idx_scans_user_day ON scans (user_id, day);

CREATE INDEX idx_scans_visitor ON scans (link_id, visitor_hash, scanned_at);

CREATE TABLE IF NOT EXISTS scan_daily (
        id        BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
        link_id   BIGINT UNSIGNED      NOT NULL,
        day       VARCHAR(10) NOT NULL,
        dimension VARCHAR(12) NOT NULL,
        value     VARCHAR(64) NOT NULL,
        total     BIGINT     NOT NULL DEFAULT 0,
        uniques   BIGINT     NOT NULL DEFAULT 0
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE UNIQUE INDEX idx_daily_unique ON scan_daily (link_id, day, dimension, value);

CREATE TABLE IF NOT EXISTS api_keys (
        id           BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
        user_id      BIGINT UNSIGNED       NOT NULL,
        name         VARCHAR(80)  NOT NULL DEFAULT '',
        prefix       VARCHAR(12)  NOT NULL,
        key_hash     VARCHAR(64)  NOT NULL,
        scopes       VARCHAR(191) NOT NULL DEFAULT 'read,write',
        last_used_at BIGINT      NULL,
        revoked_at   BIGINT      NULL,
        created_at   BIGINT      NOT NULL
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE UNIQUE INDEX idx_apikeys_hash ON api_keys (key_hash);

CREATE INDEX idx_apikeys_user ON api_keys (user_id);

CREATE TABLE IF NOT EXISTS rate_limits (
        id           BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
        bucket       VARCHAR(191) NOT NULL,
        window_start BIGINT      NOT NULL,
        hits         BIGINT      NOT NULL DEFAULT 0
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE UNIQUE INDEX idx_rl_bucket ON rate_limits (bucket, window_start);

CREATE TABLE IF NOT EXISTS audit_log (
        id         BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
        user_id    BIGINT UNSIGNED       NULL,
        action     VARCHAR(64)  NOT NULL,
        subject    VARCHAR(191) NOT NULL DEFAULT '',
        meta       MEDIUMTEXT     NULL,
        ip_hash    VARCHAR(64)  NOT NULL DEFAULT '',
        created_at BIGINT      NOT NULL
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE INDEX idx_audit_user ON audit_log (user_id, created_at);

-- ---------------------------------------------------------------
-- 002_admin_and_install
-- ---------------------------------------------------------------

ALTER TABLE users ADD COLUMN is_admin INT NOT NULL DEFAULT 0;

CREATE INDEX idx_users_admin ON users (is_admin);

CREATE TABLE IF NOT EXISTS settings (
        name       VARCHAR(64) NOT NULL PRIMARY KEY,
        value      MEDIUMTEXT    NULL,
        updated_at BIGINT     NOT NULL
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ---------------------------------------------------------------
-- Mark these migrations as applied
-- ---------------------------------------------------------------

CREATE TABLE IF NOT EXISTS migrations (id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY, name VARCHAR(191) NOT NULL UNIQUE, applied_at BIGINT NOT NULL) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

INSERT IGNORE INTO migrations (name, applied_at) VALUES ('001_init', 1790039386);
INSERT IGNORE INTO migrations (name, applied_at) VALUES ('002_admin_and_install', 1790039386);

SET FOREIGN_KEY_CHECKS = 1;

-- After importing, create your administrator with:
--   php bin/console admin:create you@example.com your-password
