<?php
declare(strict_types=1);

namespace QRoute\Core;

/**
 * Produces a plain .sql file from the migrations.
 *
 * The migrations are the single source of truth for the schema; this just
 * renders them as MySQL DDL for anyone who would rather click Import in
 * phpMyAdmin than run a command. Because it expands the same tokens the
 * migrator uses, the dump cannot describe a different schema from the one
 * the application actually creates.
 */
final class SchemaDumper
{
    public static function mysql(string $migrationsDir): string
    {
        $files = glob(rtrim($migrationsDir, '/') . '/*.php') ?: [];
        sort($files, SORT_STRING);

        $out = [];
        $out[] = '-- QRoute database schema';
        $out[] = '-- Generated by: php bin/console schema:dump';
        $out[] = '--';
        $out[] = '-- Import this in phpMyAdmin if you would rather not run migrations.';
        $out[] = '-- Create an empty database first, select it, then use the Import tab.';
        $out[] = '--';
        $out[] = '-- This file is generated from migrations/, so it always matches what';
        $out[] = '-- `php bin/console migrate` would produce. Do not edit it by hand.';
        $out[] = '';
        $out[] = 'SET NAMES utf8mb4;';
        $out[] = 'SET FOREIGN_KEY_CHECKS = 0;';
        $out[] = '';

        $applied = [];
        foreach ($files as $file) {
            $name = basename($file, '.php');
            $applied[] = $name;

            /** @var list<string> $statements */
            $statements = require $file;

            $out[] = '-- ---------------------------------------------------------------';
            $out[] = '-- ' . $name;
            $out[] = '-- ---------------------------------------------------------------';
            $out[] = '';

            foreach ($statements as $statement) {
                $sql = trim(Migrator::expandFor($statement, 'mysql'));
                if ($sql === '') {
                    continue;
                }
                $out[] = $sql . ';';
                $out[] = '';
            }
        }

        // Record the migrations as applied, so the application does not try
        // to run them again over an imported schema.
        $out[] = '-- ---------------------------------------------------------------';
        $out[] = '-- Mark these migrations as applied';
        $out[] = '-- ---------------------------------------------------------------';
        $out[] = '';
        $out[] = 'CREATE TABLE IF NOT EXISTS migrations ('
            . 'id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY, '
            . 'name VARCHAR(191) NOT NULL UNIQUE, '
            . 'applied_at BIGINT NOT NULL'
            . ') ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;';
        $out[] = '';

        $now = time();
        foreach ($applied as $name) {
            $out[] = sprintf(
                "INSERT IGNORE INTO migrations (name, applied_at) VALUES ('%s', %d);",
                str_replace("'", "''", $name),
                $now
            );
        }

        $out[] = '';
        $out[] = 'SET FOREIGN_KEY_CHECKS = 1;';
        $out[] = '';
        $out[] = '-- After importing, create your administrator with:';
        $out[] = '--   php bin/console admin:create you@example.com your-password';
        $out[] = '';

        return implode("\n", $out);
    }
}
